services:
  create-subscriber:
    build: ./
    environment:
      - MONGO_DB_URL=mongodb://host.docker.internal:27017?ssl=false
      - MONGO_DB_DATABASE=subscribers
      - MONGO_DB_COLLECTION=subscribers
    ports:
      - "9000:8080"